<?php
$title = 'User';
$this->headTitle($title);
?>
<script>
    var users = {};
</script>
<div class="action-button-pos">
    <a class="btn-floating btn-large waves-effect waves-light red" href="<?=$this->url('admin/user', array('action' => 'add'))?>">
        <i class="mdi-content-add"></i>
    </a>
</div>
<div class="well page grey lighten-5 z-depth-1">
    
    <div class="row">
        <form method="GET" action="" class="col s12">

            <div class="col s9 m7">
                <div class="input-field">
                    <i class="mdi-action-search prefix"></i>
                    <input type="text" name="q" class="validate" value="<?=$q?>" >
                    <label for="q">Suche</label>
                </div>
            </div>
            
        </form>
    </div>

    <div class="row">
        <div class="col s12">
            <table>
                <thead>
                    <tr>
                        <?php foreach($paginatorFields as $key => $label) : ?>
                            <th>
                              <a href="<?=($order_by == $key && $order == 'asc')? $this->url('admin/user',array('action' => 'index', 'order_by' => $key, 'order' => 'desc', 'q' => $q)) : $this->url('admin/user',array('action' => 'index', 'order_by' => $key, 'order' => 'asc', 'q' => $q))?>"><?=$label?></a>
                            </th>
                        <?php endforeach; ?>
                        <th>Options</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->paginator as $user):?>
                        <script>
                            users[<?=$user->id?>] = {
                        <?php foreach($paginatorFields as $key => $label) :?>
                            <?=$key?>: '<?=$user[$key]?>',
                        <?php endforeach; ?>
                            }
                        </script>
                        <tr>
                            <td><?php echo $this->escapeHtml($user->id);?></td>
                            <td><?php echo $this->escapeHtml($user->name);?></td>
                            
                            <td><?php echo $this->escapeHtml($user->email);?></td>

                            <td>
                                <a class='dropdown-button waves-effect waves-teal btn-flat' href='#' data-activates='dropdown1'><i class="small mdi-navigation-more-vert"></i></a>

                                <!-- Dropdown Structure -->
                                <ul id='dropdown1' class='dropdown-content'>
                                    <li><a href="<?php echo $this->url('admin/user', array('action'=>'edit', 'id' => $user->id));?>">edit</a></li>
                                    <li><a href="<?php echo $this->url('admin/user', array('action'=>'view', 'id' => $user->id));?>">view</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#"  onclick="return deleteConfirm(users[<?=$user->id?>], '<?php echo $this->url('admin/user', array('action'=>'delete', 'id' => $user->id));?>')">delete</a></li>
                                </ul>
                        </td>
                        </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    //toast('I am a toast!', 3000, 'rounded') 
    <?php 
             $flash = $this->flashMessenger();
             $flash->setMessageOpenFormat("toast('")
                 ->setMessageSeparatorString("',3000,'rounded');\ntoast('")
                 ->setMessageCloseString("',3000,'rounded');");

             echo $flash->render('error');
             echo $flash->render('info');
             echo $flash->render('default');
             echo $flash->render('success');
            ?>
</script>