<?php
$title = 'Userbereich';
$this->headTitle($title);
?>
<h2><?=$this->escapeHtml($title)?></h2>
<div class="row">
    <form method="GET" action="" class="form-horizontal">

        <div class="col-xs-12 col-md-6">
            <div class="form-control-wrapper">
                <input type="text" name="q" class="form-control empty" value="<?=$q?>" >
                <div for="q" class="floating-label">Suche</div>
            </div>
        </div>
    </form>
</div>
<div class="row margin-top">
    <div class="col-sm-12">
        <?php 
         $flash = $this->flashMessenger();
         $flash->setMessageOpenFormat('<div%s>
             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                 &times;
             </button>
             <p>')
             ->setMessageSeparatorString('</p><p>')
             ->setMessageCloseString('</p></div>');

         echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
         echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
         echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
         echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
         ?>
    </div>
 </div>