<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/materialize.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/main.js')
            ->prependFile($this->basePath() . '/js/materialize.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
        ; ?>

    </head>
    <body class="grey lighten-2">
        <header>
            <div class="container">
                
            </div>
            <nav class="top-nav blue">
                <div class="container">
                    <div class="nav-wrapper">
                    <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full">
                        <i class="mdi-navigation-menu"></i>
                    </a>
                        <a href="#!" class="page-title"><span class="header-text-fix"><?=$this->headTitle()->renderTitle()?></span></a>
                        
                        
                    </div>
                </div>
            </nav>
            
            <ul class="side-nav fixed" id="nav-mobile">
                <li class="logo"><a href="<?=$this->url('admin')?>"><img src="/img/banana.png" class="responsive-img"/></a></li>
                <li><a href="<?=$this->url('admin/user')?>">User</a></li>
                <li><a href="<?=$this->url('admin/user')?>">Blog</a></li>
                <li><a href="<?=$this->url('admin/user')?>">Events</a></li>
            </ul>
        </header>
        <main>
            <div class="container">
                <?php echo $this->content; ?>
            </div>
        </main>
        <footer class="page-footer blue">
            <div class="footer-copyright">
                <div class="container">
                    &copy; Copyright <?php echo date('Y') ?>, jk
                    <a class="grey-text text-lighten-4 right" href="http://www.asdf.wtf">creat0r</a>
                </div>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
            
    </body>
</html>
