<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Heavy Crunch'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/frontend.css')
                        ->prependStylesheet($this->basePath() . '/css/materialize.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/frontend.js')
            ->prependFile($this->basePath() . '/js/materialize.min.js')
            ->prependFile($this->basePath() . '/js/jquery-2.1.3.min.js')
        ; ?>

    </head>
    <body>
        <header>
            <nav class="top-nav grey darken-2">
                <div class="container">
                    <div class="nav-wrapper">
                    <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full">
                        <i class="mdi-navigation-menu"></i>
                    </a>
                        <a href="#!" class="page-title"><span class="header-text-fix"><?=$this->headTitle()->renderTitle()?></span></a>
                        
                        
                    </div>
                </div>
            </nav>
        </header>
        <main>
            <?php echo $this->content; ?>
        </main>
        <footer class="page-footer grey darken-2">
            <div class="footer-copyright">
                <div class="container">
                    &copy; Copyright <?php echo date('Y') ?>, jk
                    <a class="grey-text text-lighten-4 right" href="http://www.asdf.wtf">creat0r</a>
                </div>
            </div>
        </footer>    
        <?php echo $this->inlineScript() ?>
            
    </body>
</html>
