 <?php
$title = 'Adminpanel';
$this->headTitle($title);
?>
<div class="well page grey lighten-5 z-depth-1">
    <h4>Übersicht</h4>
    <div class="row">
        <div class="col s12 m6">
            <h5 >New Users</h5>
            <div class="collection with-header">
                <?php foreach($latestUser as $user) : ?>
                    
                    <li class="collection-item">
                        <div><?=$user->email?>
                            <a href="<?=$this->url('admin/user', array('action' => 'edit', 'user_id' => $user->id))?>" class="secondary-content"><i class="mdi-image-edit tiny"></i></a>
                        </div>
                    </li>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>