<div class="parallax-container">
    <div class="parallax">
        <img src="/img/main1.jpg">
    </div>
</div>
<div class="section white">
    <div class="row container">
        <h2 class="header">Heavy Crunch</h2>
        <p class="grey-text text-darken-3 lighten-3">Dingens, weißt schon</p>
    </div>
    <div class="row container">
        <h4 class="light"></h4>
    </div>
</div>
<div class="parallax-container">
    <div class="parallax">
        <img src="/img/main3.jpg">
    </div>
</div>  
<div class="section white">
    <div class="row container">
        <h2 class="header">Jetzt auch in ihrer nähe</h2>
        <p class="grey-text text-darken-3 lighten-3">Hier könnte man schon andere dinge einfügen</p>
    </div>
    <div class="row container">
        <h4 class="light"></h4>
    </div>
</div>